[build]
  command = "npm install"
  publish = "public"

[functions]
  node_bundler = "none"
  included_files = [
    "netlify/functions/deckRenderer.mjs",
    "netlify/functions/cardData.mjs",
    "netlify/functions/*.ttf",
    "netlify/functions/*.svg",
    "netlify/functions/*.json"
  ]

[build.environment]
  NODE_VERSION = "18.20.4"